### ISSUE TITLE
iOS, desktop/web, UWP and Business #todo

### ISSUE THREAD

**Issue by arunpt** [arunpt/wafiles-scraper#1]
- [x] WhatsApp Messenger Android
- [x] WhatsApp Messenger Android beta
- [x] WhatsApp Business Android
- [x] WhatsApp Business Android beta
- [x] WhatsApp Wear OS beta
- [ ] WhatsApp Web/Desktop
- [ ] WhatsApp Web/Desktop beta
- [ ] WhatsApp Windows UWP (beta)
- [ ] WhatsApp iOS
- [ ] WhatsApp  iOS beta

**Comment by Harsh-br0** [comment]
Do u have plans on extending this to support more applications?
It seem nice to have more compatibility
